// Public Ingenuity (Mars 2020 helicopter) flight log: 72 flights.
// Source: NASA status reports as compiled on Wikipedia's List of Ingenuity flights.
// Fields: per-flight duration (s), max altitude (m), distance (m), max groundspeed (m/s),
// plus mission notes. 'note' carries pre-flight events (aborts, delays, checkouts).
window.TRIAGE_FLIGHTS = [
 {
  "flight": 1,
  "date": "April 19, 2021",
  "sol": 58,
  "phase": "Technology Demonstration",
  "duration_s": 39.1,
  "altitude_m": 3.0,
  "distance_m": 0.05,
  "speed_ms": 0.0,
  "summary": "The first powered flight by any aircraft on another planet. While hovering, it rotated in place 96 degrees in a planned manoeuvre. Flight data was received at 11:30 UTC."
 },
 {
  "flight": 2,
  "date": "April 22, 2021",
  "sol": 61,
  "phase": "Technology Demonstration",
  "duration_s": 51.9,
  "altitude_m": 5.0,
  "distance_m": 4.0,
  "speed_ms": 0.5,
  "summary": "From initial hover, it tilted 5 degrees, allowing rotors to fly it 2 meters sideways. It stopped, hovered in place, and rotated counterclockwise, yawing from +90° to 0° to -90° to -180°, in 3 steps, to point its color camera in various directions to take photos. It flew back to the takeoff location and landed."
 },
 {
  "flight": 3,
  "date": "April 25, 2021",
  "sol": 64,
  "phase": "Technology Demonstration",
  "duration_s": 80.3,
  "altitude_m": 5.0,
  "distance_m": 99.97,
  "speed_ms": 2.0,
  "summary": "First flight to venture some distance from the deployment spot. It flew downrange 50 meters at two meters per second, stopped, hovered, then returned and landed at the departure spot. Data from the flight was received at 14:16 UTC."
 },
 {
  "flight": 4,
  "date": "April 30, 2021",
  "sol": 69,
  "phase": "Transition",
  "duration_s": 116.9,
  "altitude_m": 5.0,
  "distance_m": 270.46,
  "speed_ms": 3.5,
  "summary": "Took color images while hovering at its farthest point from takeoff. The Perseverance rover recorded both audio and video of Ingenuity in flight, making the helicopter the first interplanetary vehicle whose sound was recorded off Earth.",
  "note": "First attempt of flight 4 failed; onboard software did not transition to flight mode."
 },
 {
  "flight": 5,
  "date": "May 7, 2021",
  "sol": 76,
  "phase": "Transition",
  "duration_s": 108.2,
  "altitude_m": 10.0,
  "distance_m": 130.84,
  "speed_ms": 2.0,
  "summary": "This was the first flight to land at a new location, 129 m (423 ft) to the south. Arriving above the destination, it gained altitude, hovered, captured color terrain images, then landed at the new site, Airfield B. This flight was the last in the technology demonstration phase."
 },
 {
  "flight": 6,
  "date": "May 23, 2021",
  "sol": 91,
  "phase": "Operation Demonstration",
  "duration_s": 139.9,
  "altitude_m": 10.0,
  "distance_m": 202.39,
  "speed_ms": 4.0,
  "summary": "At each turn into the flight, colour images were taken. Near the end of the first leg of the route at 54 seconds into flight, a glitch occurred in the navigation images processing system. An image was dropped, and subsequent images with incorrect timestamps resulted in the craft tilting forward and backward up to 20 degrees, with large spikes in power consumption."
 },
 {
  "flight": 7,
  "date": "June 8, 2021",
  "sol": 107,
  "phase": "Operation Demonstration",
  "duration_s": 62.8,
  "altitude_m": 10.0,
  "distance_m": 106.34,
  "speed_ms": 4.0,
  "summary": "Flew to a new landing spot, Airfield D. The color camera was not used to prevent the glitch of flight 6 happening again.",
  "note": "First attempt of flight 7 failed; onboard software did not transition to flight mode."
 },
 {
  "flight": 8,
  "date": "June 22, 2021",
  "sol": 120,
  "phase": "Operation Demonstration",
  "duration_s": 77.4,
  "altitude_m": 10.0,
  "distance_m": 160.48,
  "speed_ms": 4.0,
  "summary": "The landing spot was about 133.5 m (438 ft) away from the Perseverance rover. As in the previous flight, the color camera was switched off, pending a software update."
 },
 {
  "flight": 9,
  "date": "July 5, 2021",
  "sol": 133,
  "phase": "Operation Demonstration",
  "duration_s": 166.4,
  "altitude_m": 10.0,
  "distance_m": 631.78,
  "speed_ms": 5.0,
  "summary": "Flew southwest, over Séítah , a prospective research location in Jezero crater . This flight strained the navigation system, which by design assumes flat ground; Séítah has uneven sand dunes. Controllers had Ingenuity partly compensate by flying slower over the more challenging part of the route."
 },
 {
  "flight": 10,
  "date": "July 24, 2021",
  "sol": 152,
  "phase": "Operation Demonstration",
  "duration_s": 165.4,
  "altitude_m": 12.0,
  "distance_m": 240.37,
  "speed_ms": 5.0,
  "summary": "The helicopter flew past 10 waypoints, including takeoff and landing. The general trajectory of the 10th flight was four chords of a broken oval, thus distance between the takeoff and landing points of about 95 meters."
 },
 {
  "flight": 11,
  "date": "August 5, 2021",
  "sol": 163,
  "phase": "Operation Demonstration",
  "duration_s": 130.9,
  "altitude_m": 12.0,
  "distance_m": 388.29,
  "speed_ms": 5.0,
  "summary": "The flight positioned the craft for a route to take photographs of South Séítah. The airfield \" H \" was the second after \"Wright Brothers Field\" in terms of the number of departures, and in terms of the total length (1069 m) and duration of these flights (481.8 s), as well as the parking time of the helicopter (3 months, from August 5 to November 6) airfield \" H \" even."
 },
 {
  "flight": 12,
  "date": "August 16, 2021",
  "sol": 174,
  "phase": "Operation Demonstration",
  "duration_s": 169.5,
  "altitude_m": 10.0,
  "distance_m": 448.21,
  "speed_ms": 4.3,
  "summary": "The return path was about 5 m (16 ft) to the side to allow another attempt to take paired images for stereo imagery. Landing was about 25 m (82 ft) east from the take-off point. This flight was decisive for the subsequent fate of the helicopter, which then got its mission extended after August."
 },
 {
  "flight": 13,
  "date": "September 5, 2021",
  "sol": 193,
  "phase": "Operation Demonstration",
  "duration_s": 160.5,
  "altitude_m": 8.0,
  "distance_m": 209.4,
  "speed_ms": 3.3,
  "summary": "The flight northeast and back concentrated on one particular ridgeline and outcrops in South Séítah."
 },
 {
  "flight": 14,
  "date": "October 24, 2021",
  "sol": 241,
  "phase": "Operation Demonstration",
  "duration_s": 23.0,
  "altitude_m": 5.0,
  "distance_m": 2.18,
  "speed_ms": 0.5,
  "summary": "The brief flight verified use of the faster rotor spin of 2700 rpm, needed during seasonal lower atmospheric density on Mars.",
  "note": "A flight attempt at a faster rotor spin rate of 2700 rpm was automatically canceled due to a servo motor anomaly. Three days earlier, September 15, Ingenuity successfully ground tested a rotor spin rate of 2800 rpm."
 },
 {
  "flight": 15,
  "date": "November 6, 2021",
  "sol": 254,
  "phase": "Operation Demonstration",
  "duration_s": 128.8,
  "altitude_m": 12.0,
  "distance_m": 410.27,
  "speed_ms": 5.0,
  "summary": "First in a series of four to seven flights on a return journey to Wright Brothers Field, due to the low atmospheric pressure and varied relief features. This leg ended in the Raised Ridges region."
 },
 {
  "flight": 16,
  "date": "November 21, 2021",
  "sol": 268,
  "phase": "Operation Demonstration",
  "duration_s": 107.9,
  "altitude_m": 10.0,
  "distance_m": 116.99,
  "speed_ms": 1.5,
  "summary": "Landed near the edge of South Séítah, prior to crossing that area on multiple impending flights."
 },
 {
  "flight": 17,
  "date": "December 5, 2021",
  "sol": 282,
  "phase": "Operation Demonstration",
  "duration_s": 116.8,
  "altitude_m": 10.0,
  "distance_m": 187.36,
  "speed_ms": 2.5,
  "summary": "Flew halfway across South Séítah along the heading of flight 9 but in the reverse direction. The helicopter lost communication with the rover during final descent, roughly 3 m (10 ft) above the ground due to 5-meter Bras outcrop ib between, but JPL believed the flight was a success, based on available telemetry."
 },
 {
  "flight": 18,
  "date": "December 15, 2021",
  "sol": 292,
  "phase": "Operation Demonstration",
  "duration_s": 124.3,
  "altitude_m": 10.0,
  "distance_m": 231.56,
  "speed_ms": 2.5,
  "summary": "Flew across South Séítah in the reverse of the flight 9 heading and landed near flight 9 takeoff spot. This was another in a series of flights returning Ingenuity to Wright Brothers Field. Airfield L has featureless sandy terrain, chosen for the lack of rocks for safe landing."
 },
 {
  "flight": 19,
  "date": "February 8, 2022",
  "sol": 345,
  "phase": "Operation Demonstration",
  "duration_s": 99.8,
  "altitude_m": 10.0,
  "distance_m": 61.19,
  "speed_ms": 1.0,
  "summary": "The helicopter flew out of South Séítah basin, across a dividing ridge and up to the main plateau, near the landing site of Flight 8. Images taken during Flight 9 were used to select a safe zone. The flight was another in a series to return to Wright Brothers Field.",
  "note": "The first attempt of flight 19 was postponed due to a dust storm approaching Jezero Crater, the first time weather delayed a flight of an airborne vehicle on a celestial object other than Earth."
 },
 {
  "flight": 20,
  "date": "February 25, 2022",
  "sol": 362,
  "phase": "Operation Demonstration",
  "duration_s": 130.3,
  "altitude_m": 10.0,
  "distance_m": 392.27,
  "speed_ms": 4.4,
  "summary": "Ingenuity continued its journey back toward its original flight zone, landing just southwest of Wright Brothers Field . From there, it will take a shortcut to the Jezero Crater river delta, flying northwest across Séítah, while Perseverance drives around the region to the \"Three Forks\" a at the foot of the slopes, on the tops of which three dry channels (sleeves) of the."
 },
 {
  "flight": 21,
  "date": "March 10, 2022",
  "sol": 375,
  "phase": "Operation Demonstration",
  "duration_s": 129.2,
  "altitude_m": 10.0,
  "distance_m": 374.4,
  "speed_ms": 3.85,
  "summary": "First in a series of flights to a position near the base of the ancient river delta in Jezero Crater to scout ahead for Perseverance ."
 },
 {
  "flight": 22,
  "date": "March 20, 2022",
  "sol": 384,
  "phase": "Operation Demonstration",
  "duration_s": 101.4,
  "altitude_m": 10.0,
  "distance_m": 70.4,
  "speed_ms": 1.0,
  "summary": "Second flight toward position near base of the delta. Ingenuity flew only 70.4 m (231 ft), not the planned ~350 m (1,150 ft)."
 },
 {
  "flight": 23,
  "date": "March 24, 2022",
  "sol": 388,
  "phase": "Operation Demonstration",
  "duration_s": 129.1,
  "altitude_m": 10.0,
  "distance_m": 374.886,
  "speed_ms": 4.0,
  "summary": "Another flight on the way to a position near the base of the delta. The flight was complex, including a sharp turn to avoid a large hill. In deciding the remaining route to the delta, the mission team considered multiple factors: thermal (temperature of helicopter parts), atmospheric, flight time, navigation drift, landing site terrain, and keeping up with the rover."
 },
 {
  "flight": 24,
  "date": "April 3, 2022",
  "sol": 398,
  "phase": "Operation Demonstration",
  "duration_s": 69.8,
  "altitude_m": 10.0,
  "distance_m": 47.54,
  "speed_ms": 1.45,
  "summary": "Fourth of five sorties crossing the Séítah region. Rotors spun at 2,537 rpm, a reduction from 2,700 rpm used since flight 14; this was a return to the slower rate of the earliest flights. Increasing air density allowed the reduction, as the thin air of the ending Martian summer was being replaced by fall's denser air."
 },
 {
  "flight": 25,
  "date": "April 8, 2022",
  "sol": 403,
  "phase": "Operation Demonstration",
  "duration_s": 161.3,
  "altitude_m": 10.0,
  "distance_m": 708.91,
  "speed_ms": 5.5,
  "summary": "Longest distance of any flight. The mission team chose a route that avoided flying over hardware that was discarded and fell to the surface during the rover's entry-descent-landing (EDL) and might have caused unexpected performance from Ingenuity's laser altimeter and visual navigation system. This flight brought the helicopter out of the Séítah region."
 },
 {
  "flight": 26,
  "date": "April 19, 2022",
  "sol": 414,
  "phase": "Operation Demonstration",
  "duration_s": 159.0,
  "altitude_m": 8.0,
  "distance_m": 391.18,
  "speed_ms": 3.8,
  "summary": "Ingenuity flew closer to the delta and took color photos of the EDL debris, including the spacecraft backshell and parachute."
 },
 {
  "flight": 27,
  "date": "April 23, 2022",
  "sol": 418,
  "phase": "Operation Demonstration",
  "duration_s": 153.9,
  "altitude_m": 10.0,
  "distance_m": 304.96,
  "speed_ms": 3.0,
  "summary": "Ingenuity flew closer to the delta capturing the images of crater ridgeline."
 },
 {
  "flight": 28,
  "date": "April 29, 2022",
  "sol": 423,
  "phase": "Operation Demonstration",
  "duration_s": 152.9,
  "altitude_m": 10.0,
  "distance_m": 420.94,
  "speed_ms": 3.6,
  "summary": "Ingenuity flew closer to the delta. This flight was the fifth in April - there has not been such an intensity of flights since the demonstration program, when 4 flights were made in April 2021."
 },
 {
  "flight": 29,
  "date": "June 11, 2022",
  "sol": 465,
  "phase": "Operation Demonstration",
  "duration_s": 66.6,
  "altitude_m": 10.0,
  "distance_m": 181.96,
  "speed_ms": 5.5,
  "summary": "First flight without the use of its inclinometer and in the cold of Martian winter.",
  "note": "High-speed spin test of the rotor blades."
 },
 {
  "flight": 30,
  "date": "August 20, 2022",
  "sol": 533,
  "phase": "Operation Demonstration",
  "duration_s": 33.3,
  "altitude_m": 5.0,
  "distance_m": 2.35,
  "speed_ms": 0.5,
  "summary": "First flight after the dust season and first in more than two months. Intended to measure how accurately Ingenuity can still fly to a specified target after a long period of inactivity.",
  "note": "One low-speed spin test of 50 rpm and one high-speed spin test of 2,573 rpm of the rotor blades to take a health check of the helicopter after it endured sandstorms and temperatures as low as −124 °F (−87 °C) during the Martian winter."
 },
 {
  "flight": 31,
  "date": "September 6, 2022",
  "sol": 550,
  "phase": "Operation Demonstration",
  "duration_s": 55.6,
  "altitude_m": 10.0,
  "distance_m": 97.2,
  "speed_ms": 4.75,
  "summary": "Reposition helicopter."
 },
 {
  "flight": 32,
  "date": "September 18, 2022",
  "sol": 561,
  "phase": "Operation Demonstration",
  "duration_s": 55.3,
  "altitude_m": 10.0,
  "distance_m": 94.36,
  "speed_ms": 4.75,
  "summary": "Continue west near edge of delta"
 },
 {
  "flight": 33,
  "date": "September 24, 2022",
  "sol": 567,
  "phase": "Operation Demonstration",
  "duration_s": 55.6,
  "altitude_m": 10.0,
  "distance_m": 112.28,
  "speed_ms": 4.75,
  "summary": "Reposition the helicopter. A small piece of foreign object debris (FOD) was seen clinging to the bottom right leg of the helicopter in footage from the navigation camera (Navcam) for a portion of this flight. It was not visible in Navcam footage from the previous flight."
 },
 {
  "flight": 34,
  "date": "November 23, 2022",
  "sol": 625,
  "phase": "Operation Demonstration",
  "duration_s": 18.3,
  "altitude_m": 5.0,
  "distance_m": 0.12,
  "speed_ms": 0.0,
  "summary": "A test of its fourth software update , with advanced navigation capabilities allowing it to safely fly up the steep terrain of the Jezero river delta, scouting ahead of the Perseverance rover."
 },
 {
  "flight": 35,
  "date": "December 3, 2022",
  "sol": 635,
  "phase": "Operation Demonstration",
  "duration_s": 52.22,
  "altitude_m": 14.0,
  "distance_m": 15.05,
  "speed_ms": 3.0,
  "summary": "Reposition helicopter."
 },
 {
  "flight": 36,
  "date": "December 10, 2022",
  "sol": 642,
  "phase": "Operation Demonstration",
  "duration_s": 60.52,
  "altitude_m": 10.0,
  "distance_m": 110.32,
  "speed_ms": 5.5,
  "summary": "Reposition helicopter."
 },
 {
  "flight": 37,
  "date": "December 17, 2022",
  "sol": 649,
  "phase": "Operation Demonstration",
  "duration_s": 55.2,
  "altitude_m": 10.0,
  "distance_m": 62.0,
  "speed_ms": 3.0,
  "summary": "Reposition helicopter."
 },
 {
  "flight": 38,
  "date": "January 5, 2023",
  "sol": 667,
  "phase": "Operation Demonstration",
  "duration_s": 74.26,
  "altitude_m": 10.0,
  "distance_m": 101.62,
  "speed_ms": 3.5,
  "summary": "Reposition helicopter. It landed in between the sand dunes as seen by Perseverance .",
  "note": "The first flight 38 attempt was rejected after onboard software did not transition to flight mode because of the approach of a short, but severe, dust storm."
 },
 {
  "flight": 39,
  "date": "January 11, 2023",
  "sol": 673,
  "phase": "Operation Demonstration",
  "duration_s": 78.7,
  "altitude_m": 10.0,
  "distance_m": 143.76,
  "speed_ms": 4.0,
  "summary": "Test new flight software."
 },
 {
  "flight": 40,
  "date": "January 19, 2023",
  "sol": 681,
  "phase": "Operation Demonstration",
  "duration_s": 91.6,
  "altitude_m": 10.0,
  "distance_m": 177.49,
  "speed_ms": 3.2,
  "summary": "Reposition helicopter."
 },
 {
  "flight": 41,
  "date": "January 27, 2023",
  "sol": 689,
  "phase": "Operation Demonstration",
  "duration_s": 109.1,
  "altitude_m": 10.0,
  "distance_m": 181.35,
  "speed_ms": 3.0,
  "summary": "Scouting for Perseverance and photographing science targets."
 },
 {
  "flight": 42,
  "date": "February 5, 2023",
  "sol": 697,
  "phase": "Operation Demonstration",
  "duration_s": 137.2,
  "altitude_m": 10.0,
  "distance_m": 255.47,
  "speed_ms": 3.0,
  "summary": "Scouting for Perseverance and photographing science targets."
 },
 {
  "flight": 43,
  "date": "February 16, 2023",
  "sol": 708,
  "phase": "Operation Demonstration",
  "duration_s": 146.0,
  "altitude_m": 12.0,
  "distance_m": 390.0,
  "speed_ms": 4.0,
  "summary": "Ingenuity commenced a series of frequent flights from this point through March to keep ahead of Perseverance , whose large no-fly exclusion zone prevents the two passing in the confines of the canyon. Ingenuity must stay ahead of Perseverance in order to scout for it. It also photographs science targets en route."
 },
 {
  "flight": 44,
  "date": "February 19, 2023",
  "sol": 711,
  "phase": "Operation Demonstration",
  "duration_s": 141.26,
  "altitude_m": 12.0,
  "distance_m": 324.12,
  "speed_ms": 3.5,
  "summary": "Scouting, keeping ahead of Perseverance in the canyon, and photographing science targets."
 },
 {
  "flight": 45,
  "date": "February 22, 2023",
  "sol": 714,
  "phase": "Operation Demonstration",
  "duration_s": 144.54,
  "altitude_m": 12.0,
  "distance_m": 502.6,
  "speed_ms": 6.0,
  "summary": "Scouting, keeping ahead of Perseverance in the canyon, and photographing science targets."
 },
 {
  "flight": 46,
  "date": "February 25, 2023",
  "sol": 717,
  "phase": "Operation Demonstration",
  "duration_s": 135.86,
  "altitude_m": 12.0,
  "distance_m": 445.381,
  "speed_ms": 5.3,
  "summary": "Scouting, keeping ahead of Perseverance in the canyon, and photographing science targets."
 },
 {
  "flight": 47,
  "date": "March 9, 2023",
  "sol": 729,
  "phase": "Operation Demonstration",
  "duration_s": 138.69,
  "altitude_m": 12.0,
  "distance_m": 449.75,
  "speed_ms": 5.3,
  "summary": "Scouting Tenby, though the color camera narrowly missed the main area of interest by a few degrees outside the field of view; keeping ahead of Perseverance in the canyon; and photographing science targets. Imaged by Perseverance while taking off from Airfield Theta (θ)."
 },
 {
  "flight": 48,
  "date": "March 22, 2023",
  "sol": 741,
  "phase": "Operation Demonstration",
  "duration_s": 149.9,
  "altitude_m": 12.0,
  "distance_m": 387.56,
  "speed_ms": 4.65,
  "summary": "Scouting Castell Henllys successfully, producing high resolution pictures of the area, keeping ahead of Perseverance in the canyon, and photographing science targets."
 },
 {
  "flight": 49,
  "date": "April 2, 2023",
  "sol": 752,
  "phase": "Operation Demonstration",
  "duration_s": 142.71,
  "altitude_m": 16.0,
  "distance_m": 278.99,
  "speed_ms": 6.5,
  "summary": "Scouting, keeping ahead of Perseverance in the canyon and photographing the Southern wall of Belva Crater, again narrowly missing the main area of interest by a few degrees outside the field of view. It snapped the highest suborbital picture taken of the Martian surface since landing.",
  "note": "Two aborted flight attempts, the first due to high winds cooling the battery below preflight check levels, and the second due to a minor command sequencing glitch."
 },
 {
  "flight": 50,
  "date": "April 13, 2023",
  "sol": 763,
  "phase": "Operation Demonstration",
  "duration_s": 145.65,
  "altitude_m": 18.0,
  "distance_m": 304.761,
  "speed_ms": 4.6,
  "summary": "After the previous flight, a communications blackout with Ingenuity occurred due to terrain between it and the rover blocking radio signals until April 11 (Sol 761), when the rover came within range. Also, the base station antenna on the rover is located on the right side and is low enough for various parts of the rover to occlude radio transmission."
 },
 {
  "flight": 51,
  "date": "April 23, 2023",
  "sol": 772,
  "phase": "Operation Demonstration",
  "duration_s": 136.9,
  "altitude_m": 12.0,
  "distance_m": 190.701,
  "speed_ms": 4.0,
  "summary": "Scouting, helping to identify locations of interest for the Perseverance ."
 },
 {
  "flight": 52,
  "date": "April 27, 2023",
  "sol": 776,
  "phase": "Operation Demonstration",
  "duration_s": 138.88,
  "altitude_m": 12.0,
  "distance_m": 363.176,
  "speed_ms": 3.7,
  "summary": "Scouting, helping to identify locations of interest for Perseverance . The flight succeeded on the scheduled date, but images and other confirming data were finally received on June 28, 2023 (Sol 837). The rover and helicopter were out of communication with each other for 63 days, because a hill stood between them, blocking radio signals."
 },
 {
  "flight": 53,
  "date": "July 22, 2023",
  "sol": 860,
  "phase": "Operation Demonstration",
  "duration_s": 74.85,
  "altitude_m": 5.0,
  "distance_m": 142.618,
  "speed_ms": 2.5,
  "summary": "Scouting flight for Perseverance to the north. The low level (5 m or 16 ft) flight intended to create a detailed terrain record was cut short by an automatic contingency landing instruction via a program called ‘LAND_NOW’, prior to the intended ascent to 10 m (33 ft) to assess landing hazards. This is the first inflight abort of the rotorcraft."
 },
 {
  "flight": 54,
  "date": "August 4, 2023",
  "sol": 873,
  "phase": "Operation Demonstration",
  "duration_s": 24.37,
  "altitude_m": 5.0,
  "distance_m": 0.026,
  "speed_ms": 0.0,
  "summary": "Following an investigation of flight 53's truncated flight plan, this pop-up ascent was designed to test software modifications and confirm the reasons for the autoland instruction on flight 53."
 },
 {
  "flight": 55,
  "date": "August 12, 2023",
  "sol": 881,
  "phase": "Operation Demonstration",
  "duration_s": 142.9,
  "altitude_m": 10.0,
  "distance_m": 265.405,
  "speed_ms": 4.7,
  "summary": "No advice from NASA regarding purpose."
 },
 {
  "flight": 56,
  "date": "August 26, 2023",
  "sol": 894,
  "phase": "Operation Demonstration",
  "duration_s": 140.9,
  "altitude_m": 12.0,
  "distance_m": 435.761,
  "speed_ms": 5.3,
  "summary": "Reposition."
 },
 {
  "flight": 57,
  "date": "September 3, 2023",
  "sol": 902,
  "phase": "Operation Demonstration",
  "duration_s": 128.6,
  "altitude_m": 10.0,
  "distance_m": 222.607,
  "speed_ms": 3.0,
  "summary": "Photograph science targets."
 },
 {
  "flight": 58,
  "date": "September 11, 2023",
  "sol": 910,
  "phase": "Operation Demonstration",
  "duration_s": 106.8,
  "altitude_m": 10.0,
  "distance_m": 175.597,
  "speed_ms": 3.0,
  "summary": "Reposition, scout the margin carbonate unit for Perseverance"
 },
 {
  "flight": 59,
  "date": "September 16, 2023",
  "sol": 915,
  "phase": "Operation Demonstration",
  "duration_s": 142.6,
  "altitude_m": 20.0,
  "distance_m": 1.138,
  "speed_ms": 0.0,
  "summary": "Pop-up flight; new record altitude."
 },
 {
  "flight": 60,
  "date": "September 26, 2023",
  "sol": 924,
  "phase": "Operation Demonstration",
  "duration_s": 132.8,
  "altitude_m": 16.0,
  "distance_m": 353.345,
  "speed_ms": 8.0,
  "summary": "Reposition helicopter and photograph science targets."
 },
 {
  "flight": 61,
  "date": "October 5, 2023",
  "sol": 933,
  "phase": "Operation Demonstration",
  "duration_s": 129.5,
  "altitude_m": 24.0,
  "distance_m": 0.341,
  "speed_ms": 0.0,
  "summary": "Expansion of flight envelope; pop-up flight; new record altitude."
 },
 {
  "flight": 62,
  "date": "October 12, 2023",
  "sol": 940,
  "phase": "Operation Demonstration",
  "duration_s": 121.07,
  "altitude_m": 18.0,
  "distance_m": 291.691,
  "speed_ms": 10.0,
  "summary": "Expansion of flight envelope; new record groundspeed."
 },
 {
  "flight": 63,
  "date": "October 19, 2023",
  "sol": 947,
  "phase": "Operation Demonstration",
  "duration_s": 142.6,
  "altitude_m": 12.0,
  "distance_m": 591.457,
  "speed_ms": 6.3,
  "summary": "Reposition"
 },
 {
  "flight": 64,
  "date": "October 27, 2023",
  "sol": 955,
  "phase": "Operation Demonstration",
  "duration_s": 139.1,
  "altitude_m": 12.0,
  "distance_m": 411.0,
  "speed_ms": 5.8,
  "summary": "Reposition"
 },
 {
  "flight": 65,
  "date": "November 2, 2023",
  "sol": 960,
  "phase": "Operation Demonstration",
  "duration_s": 48.0,
  "altitude_m": 10.0,
  "distance_m": 7.0,
  "speed_ms": 1.0,
  "summary": "Reposition."
 },
 {
  "flight": 66,
  "date": "November 3, 2023",
  "sol": 961,
  "phase": "Operation Demonstration",
  "duration_s": 23.0,
  "altitude_m": 3.0,
  "distance_m": 0.57,
  "speed_ms": 1.0,
  "summary": "Reposition."
 },
 {
  "flight": 67,
  "date": "December 2, 2023",
  "sol": 990,
  "phase": "Operation Demonstration",
  "duration_s": 135.9,
  "altitude_m": 12.0,
  "distance_m": 399.06,
  "speed_ms": 5.3,
  "summary": "Reposition.",
  "note": "Solar conjunction, when Mars is behind the Sun, interrupts communications between NASA and Ingenuity . During the pause, Ingenuity was programmed to take color photos to study the movement of sand, which can be a threat to rovers."
 },
 {
  "flight": 68,
  "date": "December 15, 2023",
  "sol": 1002,
  "phase": "Operation Demonstration",
  "duration_s": 131.1,
  "altitude_m": 16.0,
  "distance_m": 702.28,
  "speed_ms": 10.0,
  "summary": "Flight test."
 },
 {
  "flight": 69,
  "date": "December 20, 2023",
  "sol": 1007,
  "phase": "Operation Demonstration",
  "duration_s": 135.4,
  "altitude_m": 16.0,
  "distance_m": 702.27,
  "speed_ms": 10.0,
  "summary": "Flight test."
 },
 {
  "flight": 70,
  "date": "December 22, 2023",
  "sol": 1009,
  "phase": "Operation Demonstration",
  "duration_s": 132.9,
  "altitude_m": 12.0,
  "distance_m": 255.109,
  "speed_ms": 3.0,
  "summary": "Reposition."
 },
 {
  "flight": 71,
  "date": "January 6, 2024",
  "sol": 1023,
  "phase": "Operation Demonstration",
  "duration_s": 34.96,
  "altitude_m": 12.0,
  "distance_m": 67.936,
  "speed_ms": 7.0,
  "summary": "The planned flight was terminated early for technical reasons."
 },
 {
  "flight": 72,
  "date": "January 18, 2024",
  "sol": 1035,
  "phase": "Operation Demonstration",
  "duration_s": 32.2,
  "altitude_m": 12.0,
  "distance_m": 10.303,
  "speed_ms": 0.0,
  "summary": "Ingenuity was permanently grounded following this flight, a brief ascent to check the helicopter's systems after the previous flight's unplanned termination. Data sent via Perseverance indicated that the helicopter successfully climbed to its assigned altitude, but lost communication with Perseverance before landing because the vehicles were positioned out of line-of-sight."
 }
];
